### ISSUE TITLE
TaliaBeeIO Error

### ISSUE THREAD

**Issue by mesutbicer** [beyaznet/python-taliabeeio-module#1]
Hi beyaznet family,

I have bought a new medioex card and raspberry PI, and tested this card via original pe2a medioex c and cpp library; there is no fault. Moreover, I tested this pymedioex library (https://github.com/bayraktarulku/pymedioex). Similarly there is no fault. But, I couldnt see "read instant temperature", "read all digital inputs" and "read all digital outputs" methods in pymedioex library. 

In TaliaBeeIO module, I realized these points solved. That's why, I installed taliabeeio module to my python3.6. Then I tried to test via below commands on idle3.6 and get these errors:

==================================================================
Python 3.6.4 (default, Feb  8 2018, 17:48:44) 

[GCC 4.6.3] on linux
Type "copyright", "credits" or "license()" for more information.

>>> from taliabeeio import TaliaBeeIO
>>> io = TaliaBeeIO()
>>> print(io.temperature)

Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
     (self.host, self.port), self.timeout, **extra_kw)
   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
     raise err
   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
     sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
     chunked=chunked)
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
     conn.request(method, url, **httplib_request_kw)
   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
     self._send_request(method, url, body, headers, encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
     self.endheaders(body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
     self.connect()
   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
     conn = self._new_conn()
   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
     self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x74982050>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
     _stacktrace=sys.exc_info()[2])
   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
     raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /api/temperature/read (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74982050>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "<pyshell#2>", line 1, in <module>
     print(io.temperature)
   File "/usr/local/lib/python3.6/site-packages/taliabeeio/__init__.py", line 27, in __getattribute__
     return super(TaliaBeeIO, self).__getattribute__(attr)
   File "/usr/local/lib/python3.6/site-packages/taliabeeio/__init__.py", line 142, in temperature
     return self._call(url)
   File "/usr/local/lib/python3.6/site-packages/taliabeeio/__init__.py", line 59, in _call
     r = requests.get(url, timeout=self.timeout, verify=self.verify)
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
     return request('get', url, params=params, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
     raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /api/temperature/read (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74982050>: Failed to establish a new connection: [Errno 111] Connection refused',))
>>> 
==================================================================

By the way, all requirements satisfied by my raspian OS like that.
==================================================================
root@raspberrypi:/home/pi/medIOEx-Example/MedIOEx# sudo pip3.6 install requests
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests)
==================================================================

How to fix these error? Can you help me?

Thank you in advance.

**Comment by nejdetckenobi** [comment]
Hi Mesut,

The module you installed is just a client of a web api which is provided by another project of ours named [TaliaBee](https://github.com/beyaznet/TaliaBee). Please follow [that instructions](https://github.com/beyaznet/TaliaBee#installation) to install and run it with your Raspberry Pi. Then type your commands again and you'll be just fine. Without a running API side, TaliaBeeIO will surely give you a `connection refused` error because there's no running API to connect.

The package (pymedioex)[https://github.com/bayraktarulku/pymedioex] uses the C library and communicates with the hardware directly. That's why you got no error while using pymedioex. 

You should install [TaliaBee](https://github.com/beyaznet/TaliaBee) to your Raspberry Pi first then you'll be able to connect to it via TaliaBeeIO.

We are looking forward to hearing more from you!

(The problem can also be caused by older versions of Raspbian just for readers' information. Use up-to-date versions.)

**Comment by mesutbicer** [comment]
I have done these instructions to. But I couldnt open web interface like your demo box. (One note: 127.0.0.1:5000 shows basic another MedIOEX test suite). How can I access this elegant taliabee web user interface (https://github.com/beyaznet/TaliaBee#interfaces )?

**Comment by mesutbicer** [comment]
Thank you so much for your help nejdetckenobi and emrah.com. I installed and run the library 2 days ago, but now I had the opportunity to write here. Library installation is ok. Thank you again.
